import { io, type Socket } from "socket.io-client";
import "./style.css";

const SERVER_URL = import.meta.env.VITE_SERVER_URL || "http://localhost:3000";
type Message = { id:string; channel:string; type:"user"|"system"; nickname?:string; text:string; createdAt:number };
type Channel = { channel:string; gameId:string; roomCode:string; messageCount:number; activeUsers:number; lastMessageAt:number };
type GameRoom = { gameId:"bobartist"|"yacht-dice"; roomCode:string; state:string; playerCount:number; maxPlayers:number; players:Array<{id:string;nickname:string;isHost:boolean}>; detail:Record<string,string|number|boolean|null>; updatedAt:number };
type NicknameHistory = { nickname:string; firstUsedAt:number; lastUsedAt:number; useCount:number };
type AccessHistory = { gameId:string; roomCode:string; joinedAt:number; lastSeenAt:number };
type PlayerRecord = { clientId:string; connectionKey:string; maskedIp:string; firstSeenAt:number; lastSeenAt:number; connectionCount:number; nicknames:NicknameHistory[]; accesses:AccessHistory[] };
type Snapshot = { channels:Channel[]; histories:Record<string,Message[]>; gameRooms:GameRoom[]; players:PlayerRecord[] };
type Tab = "chat"|"games"|"players";
let socket: Socket | null = null;
let authenticated = false;
let snapshot: Snapshot = { channels:[], histories:{}, gameRooms:[], players:[] };
let selected = "all";
let query = "";
let tab: Tab = "chat";

const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
const time=(v:number)=>new Date(v).toLocaleString("ko-KR",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"});
const gameName=(id:string)=>id==="bobartist"?"BobArtist":"Yacht Dice";
function root(){ const el=document.querySelector<HTMLDivElement>("#app"); if(!el) throw new Error("#app not found"); return el; }
function allMessages():Message[]{ return Object.values(snapshot.histories).flat().sort((a,b)=>a.createdAt-b.createdAt); }
function filteredMessages():Message[]{ const list=selected==="all"?allMessages():(snapshot.histories[selected]||[]); const q=query.trim().toLowerCase(); return q?list.filter(m=>`${m.channel} ${m.nickname||"system"} ${m.text}`.toLowerCase().includes(q)):list; }
function filteredPlayers():PlayerRecord[]{ const q=query.trim().toLowerCase(); return q?snapshot.players.filter(p=>`${p.connectionKey} ${p.maskedIp} ${p.nicknames.map(n=>n.nickname).join(" ")} ${p.accesses.map(a=>`${a.gameId} ${a.roomCode}`).join(" ")}`.toLowerCase().includes(q)):snapshot.players; }
function filteredRooms():GameRoom[]{ const q=query.trim().toLowerCase(); return q?snapshot.gameRooms.filter(r=>`${r.gameId} ${r.roomCode} ${r.state} ${r.players.map(p=>p.nickname).join(" ")}`.toLowerCase().includes(q)):snapshot.gameRooms; }
function renderLogin(message=""){ root().innerHTML=`<main class="admin-login"><form><p>BOBPLATFORM ADMIN</p><h1>Control Center</h1><input type="password" autocomplete="current-password" placeholder="관리자 비밀번호" autofocus><button>로그인</button><small>${esc(message)}</small><a href="#/">← 플랫폼으로 돌아가기</a></form></main>`; root().querySelector("form")?.addEventListener("submit",e=>{e.preventDefault();const password=root().querySelector<HTMLInputElement>("input")?.value||"";socket?.emit("admin:chat:login",{password},(r:{ok:boolean;message?:string})=>{if(r.ok){authenticated=true;render();socket?.emit("admin:chat:request-snapshot");}else renderLogin(r.message);});}); }
function tabButtons(){return `<nav class="admin-tabs"><button data-tab="chat" class="${tab==="chat"?"active":""}">채팅 로그</button><button data-tab="games" class="${tab==="games"?"active":""}">게임 상태</button><button data-tab="players" class="${tab==="players"?"active":""}">플레이어 이력</button></nav>`;}
function renderChat(){const channels=snapshot.channels;const messages=filteredMessages();return `<section class="admin-layout"><aside><button class="channel ${selected==="all"?"active":""}" data-channel="all"><strong>전체 채널</strong><span>${allMessages().length}건</span></button>${channels.map(c=>`<button class="channel ${selected===c.channel?"active":""}" data-channel="${esc(c.channel)}"><strong>${gameName(c.gameId)} · ${c.roomCode}</strong><span>${c.activeUsers}명 · ${c.messageCount}건</span><small>${esc(c.channel)}</small></button>`).join("")||`<p class="empty">아직 생성된 채널이 없습니다.</p>`}</aside><article><div class="toolbar"><strong>${selected==="all"?"전체 로그":esc(selected)}</strong><input id="adminSearch" value="${esc(query)}" placeholder="닉네임, 방 코드, 메시지 검색"></div><div class="logs">${messages.map(m=>`<div class="log ${m.type}"><time>${time(m.createdAt)}</time><b>${m.type==="system"?"SYSTEM":esc(m.nickname||"익명")}</b><span>${esc(m.text)}</span><small>${esc(m.channel)}</small></div>`).join("")||`<p class="empty">표시할 메시지가 없습니다.</p>`}</div></article></section>`;}
function detailRows(detail:GameRoom["detail"]){return Object.entries(detail).map(([k,v])=>`<span><small>${esc(k)}</small><b>${esc(String(v??"-"))}</b></span>`).join("");}
function renderGames(){const rooms=filteredRooms();return `<section class="single-panel"><div class="toolbar"><strong>현재 활성 방과 진행 상태</strong><input id="adminSearch" value="${esc(query)}" placeholder="게임, 방 코드, 닉네임 검색"></div><div class="room-grid">${rooms.map(r=>`<article class="room-card"><header><div><p>${gameName(r.gameId)}</p><h2>${r.roomCode}</h2></div><b class="state ${esc(r.state)}">${esc(r.state)}</b></header><div class="room-meta"><span>${r.playerCount} / ${r.maxPlayers}명</span><time>갱신 ${time(r.updatedAt)}</time></div><div class="detail-grid">${detailRows(r.detail)}</div><h3>플레이어</h3><ul>${r.players.map(p=>`<li><span>${esc(p.nickname)}</span>${p.isHost?"<b>HOST</b>":""}</li>`).join("")||"<li>플레이어 없음</li>"}</ul></article>`).join("")||`<p class="empty">현재 활성 게임 방이 없습니다.</p>`}</div></section>`;}
function renderPlayers(){const players=filteredPlayers();return `<section class="single-panel"><div class="toolbar"><strong>동일 Client ID 기반 접속 이력</strong><input id="adminSearch" value="${esc(query)}" placeholder="닉네임, 식별자, 마스킹 IP 검색"></div><div class="player-list">${players.map(p=>`<details class="player-card"><summary><div><strong>${esc(p.connectionKey)}</strong><small>${esc(p.maskedIp)}</small></div><div><b>${esc(p.nicknames[0]?.nickname||"익명")}</b><span>${p.connectionCount}회 · ${time(p.lastSeenAt)}</span></div></summary><section><div class="player-facts"><span>최초 접속 <b>${time(p.firstSeenAt)}</b></span><span>최근 접속 <b>${time(p.lastSeenAt)}</b></span><span>접속 횟수 <b>${p.connectionCount}회</b></span></div><h3>닉네임 변경 이력</h3><ol>${p.nicknames.map(n=>`<li><b>${esc(n.nickname)}</b><span>${time(n.firstUsedAt)} → ${time(n.lastUsedAt)} · ${n.useCount}회</span></li>`).join("")}</ol><h3>최근 게임 접속</h3><ol>${p.accesses.slice(0,10).map(a=>`<li><b>${gameName(a.gameId)} · ${a.roomCode}</b><span>${time(a.joinedAt)}</span></li>`).join("")||"<li>기록 없음</li>"}</ol></section></details>`).join("")||`<p class="empty">아직 플레이어 이력이 없습니다.</p>`}</div><p class="privacy-note">IP는 일부만 마스킹되며, 동일 IP가 반드시 동일 사용자를 뜻하지 않습니다. 기록은 서버 메모리에만 유지됩니다.</p></section>`;}
function render(){ if(!authenticated){renderLogin();return;} root().innerHTML=`<main class="admin-page"><header><div><p>BOBPLATFORM ADMIN</p><h1>BobPlatform Control Center</h1></div><div><b>활성 방 ${snapshot.gameRooms.length}</b><b>채널 ${snapshot.channels.filter(c=>c.activeUsers>0).length}</b><b>플레이어 이력 ${snapshot.players.length}</b><a href="#/">플랫폼</a></div></header>${tabButtons()}${tab==="chat"?renderChat():tab==="games"?renderGames():renderPlayers()}</main>`; root().querySelectorAll<HTMLButtonElement>("[data-tab]").forEach(b=>b.onclick=()=>{tab=(b.dataset.tab||"chat") as Tab;query="";render();}); root().querySelectorAll<HTMLButtonElement>("[data-channel]").forEach(b=>b.onclick=()=>{selected=b.dataset.channel||"all";render();}); const search=root().querySelector<HTMLInputElement>("#adminSearch"); search?.addEventListener("input",()=>{query=search.value;render();requestAnimationFrame(()=>{const i=root().querySelector<HTMLInputElement>("#adminSearch");i?.focus();i?.setSelectionRange(i.value.length,i.value.length);});}); requestAnimationFrame(()=>{const logs=root().querySelector<HTMLElement>(".logs");if(logs)logs.scrollTop=logs.scrollHeight;}); }
export function mountAdminChat(){ document.title="Control Center | BobPlatform"; document.body.className="admin-body"; socket=io(SERVER_URL,{transports:["websocket","polling"]}); socket.on("admin:chat:snapshot",(data:Snapshot)=>{snapshot={channels:data.channels||[],histories:data.histories||{},gameRooms:data.gameRooms||[],players:data.players||[]};render();}); socket.on("admin:chat:message",()=>socket?.emit("admin:chat:request-snapshot")); socket.on("admin:chat:error",(p:{message?:string})=>{if(!authenticated)renderLogin(p.message);}); renderLogin(); }
