import { io, type Socket } from "socket.io-client";
import "./style.css";

const SERVER_URL = import.meta.env.VITE_SERVER_URL || "http://localhost:3000";
type Message = { id:string; channel:string; type:"user"|"system"; nickname?:string; text:string; createdAt:number };
type Channel = { channel:string; gameId:string; roomCode:string; messageCount:number; activeUsers:number; lastMessageAt:number };
type Snapshot = { channels:Channel[]; histories:Record<string,Message[]> };
let socket: Socket | null = null;
let authenticated = false;
let snapshot: Snapshot = { channels:[], histories:{} };
let selected = "all";
let query = "";

const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
const time=(v:number)=>new Date(v).toLocaleString("ko-KR",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"});
function root(){ const el=document.querySelector<HTMLDivElement>("#app"); if(!el) throw new Error("#app not found"); return el; }
function allMessages():Message[]{ return Object.values(snapshot.histories).flat().sort((a,b)=>a.createdAt-b.createdAt); }
function filteredMessages():Message[]{ const list=selected==="all"?allMessages():(snapshot.histories[selected]||[]); const q=query.trim().toLowerCase(); return q?list.filter(m=>`${m.channel} ${m.nickname||"system"} ${m.text}`.toLowerCase().includes(q)):list; }
function renderLogin(message=""){ root().innerHTML=`<main class="admin-login"><form><p>BOBPLATFORM ADMIN</p><h1>채팅 모니터</h1><input type="password" autocomplete="current-password" placeholder="관리자 비밀번호" autofocus><button>로그인</button><small>${esc(message)}</small><a href="#/">← 플랫폼으로 돌아가기</a></form></main>`; root().querySelector("form")?.addEventListener("submit",e=>{e.preventDefault();const password=root().querySelector<HTMLInputElement>("input")?.value||"";socket?.emit("admin:chat:login",{password},(r:{ok:boolean;message?:string})=>{if(r.ok){authenticated=true;render();socket?.emit("admin:chat:request-snapshot");}else renderLogin(r.message);});}); }
function render(){ if(!authenticated){renderLogin();return;} const channels=snapshot.channels; const messages=filteredMessages(); root().innerHTML=`<main class="admin-page"><header><div><p>BOBPLATFORM ADMIN</p><h1>실시간 채팅 모니터</h1></div><div><b>활성 채널 ${channels.filter(c=>c.activeUsers>0).length}</b><b>접속 ${channels.reduce((n,c)=>n+c.activeUsers,0)}</b><b>로그 ${allMessages().length}</b><a href="#/">플랫폼</a></div></header><section class="admin-layout"><aside><button class="channel ${selected==="all"?"active":""}" data-channel="all"><strong>전체 채널</strong><span>${allMessages().length}건</span></button>${channels.map(c=>`<button class="channel ${selected===c.channel?"active":""}" data-channel="${esc(c.channel)}"><strong>${c.gameId==="bobartist"?"BobArtist":"Yacht Dice"} · ${c.roomCode}</strong><span>${c.activeUsers}명 · ${c.messageCount}건</span><small>${esc(c.channel)}</small></button>`).join("")||`<p class="empty">아직 생성된 채널이 없습니다.</p>`}</aside><article><div class="toolbar"><strong>${selected==="all"?"전체 로그":esc(selected)}</strong><input id="adminSearch" value="${esc(query)}" placeholder="닉네임, 방 코드, 메시지 검색"></div><div class="logs">${messages.map(m=>`<div class="log ${m.type}"><time>${time(m.createdAt)}</time><b>${m.type==="system"?"SYSTEM":esc(m.nickname||"익명")}</b><span>${esc(m.text)}</span><small>${esc(m.channel)}</small></div>`).join("")||`<p class="empty">표시할 메시지가 없습니다.</p>`}</div></article></section></main>`; root().querySelectorAll<HTMLButtonElement>("[data-channel]").forEach(b=>b.onclick=()=>{selected=b.dataset.channel||"all";render();}); const search=root().querySelector<HTMLInputElement>("#adminSearch"); search?.addEventListener("input",()=>{query=search.value;render();requestAnimationFrame(()=>{const i=root().querySelector<HTMLInputElement>("#adminSearch");i?.focus();i?.setSelectionRange(i.value.length,i.value.length);});}); requestAnimationFrame(()=>{const logs=root().querySelector<HTMLElement>(".logs");if(logs)logs.scrollTop=logs.scrollHeight;}); }
export function mountAdminChat(){ document.title="채팅 모니터 | BobPlatform"; document.body.className="admin-body"; socket=io(SERVER_URL,{transports:["websocket","polling"]}); socket.on("admin:chat:snapshot",(data:Snapshot)=>{snapshot=data;render();}); socket.on("admin:chat:message",()=>socket?.emit("admin:chat:request-snapshot")); socket.on("admin:chat:error",(p:{message?:string})=>{if(!authenticated)renderLogin(p.message);}); renderLogin(); }
